breez/breez

init.go, log.go
In case Breez is terminated some services may want to log and since logging is done through lightninglib this is not available and will cause a SIGABRT. But there is still value in logging to breez.log when this is available so add a runtime check to see if lightninglib is initialised
=> Don't log unless lightninglib is ready

bindings/api.go, doubleratchet/doublerachet.go, doubleratchet/doubleratchet_test.go
This PR is to make the sessionID mandatory for creating new ratchet sessions.
This is because session identifiers identify sessions between users and may be controlled by an external server.
=> make sessionID mandatory for creating new sessions

account.go
This PR calculate the account and send notification on account change every 1 minute until the channel is opened.
This is temporary to overcome the inability to get it properly from lightningLib right now.
=> poll for open channel untill we have a better way

bootstrap/bootstrap.go, config/init.go, init.go, sync/chainservice.go, sync/init.go
This PR moves the config parsing and validating to its own package.
The main reason is so we can run a dedicated and self contained code, like job, shared neutrino for example, without depending on breez main package.
Since breez depends on this shared code the opposite dependency is not even possible, creating circular dependency.
In addition it isolate the configuration from the entry points (lightninglib, job) allowing multiple entry points operate without depending on each other.
=> Package config

chainservice/init.go, sync/db.go, sync/job.go
This PR is about letting the sync job write and fetch the last compact filter that was downloaded.
Now that neutrino is running in the background its `ChainTip` is progressing without downloading filters and we can't (it is wrong to) count on it a point to start the next download batch.
Instead we mark the height of the last filter that was downloaded and start from there.
In addition an adjustment to neutrino query timeout was done to 10 seconds.
=> Persiste last filter

connect.go, payments.go
This PR adds waiting for routing node connected before actions that needs it.
It will enable the app to be seemed as available immediately.
=> Connect on action

chainservice/init.go, init.go, sync/job.go
This PR solves the problem where neutrino is kept alive when is not used by either the job or the breez daemon.
In order to makes things simpler at the high level parts (job, app) and remove the need for them to deal with synchronization code, the design here is to use reference count at the chainservice package.
Instead of a singleton pattern the callers now can retrieve the shared service but must call the cleanup function when they no longer use the service. 
At the chainservice package the reference count is maintained and if reaches zero the service is stopped.
=> Stop non-used neutrino

account.go, backup/init.go, backup/interface.go, backup/manager.go, backup/manager_test.go, init.go
In this PR we add unit tests for the backup package.
The formal coverage is 42% but given the fact that half of the code is the actual google drive implementation (this is not tested), the infrastructure itself is over 90% covered.
In order to add these tests several changes needed to be done in the package so the code will be more testable.
The biggest change was to move the prepareData implementation out of the package and use a small function interface instead. This way we could mock it on testing and reduce the dependencies in the backup package itself that is now no longer depends on breez and breezdb packages.
=> Backup tests

sync/db.go, sync/job.go
This PR adds rate limit to the sync job.
We ensure now that the job won't run more than 1 time in a 10 minutes interval. This is important because there could be various triggers that starts the job (notifications, local scheduling etc...) and the way these triggers are aggregated depend on the OS. Therefore, this commits ensures there won't be a case where multiple jobs will run in a short interval, preventing resource problems in mobile.
=> Job rate limit

bindings/api.go, payments.go, payments_test.go
This PR ensures the serialized memo is marshaled to hex before we put it into the payment request instead of just creating string from bytes.
It also ensured the un-marshaling works the same.
=> ctp: Fix memo marshaling.

connect.go
In this PR we make sure the client keeps trying to connect to routing node in case we still don' t have an opened channel.
Before this commit, if from some reason we got a disconnect event after the initial connection and before the channel was opened, no further attempts were done to connect to the routing node.
This logic is required only when no  channel was opened since in case a channel exists it is handled automatically by lightning lib.
=> connect: retry connect to node before got channel.

sync/channelswatcher.go
In this PR we skip watching channels with zero local balance.
The main goal is to prevent sending warning notification to the user in that case such channels
is closed while he is offline as it doesn't really affect any of his funds.
=> channelswatcher: ignore empty channels.

app.go, bindings/api.go, db/db.go, db/db_test.go, db/syncstatus.go, go.sum, lnnode/notifier.go, sync/job.go
This PR caches the last synced header timestamp after every sync, whether it is from the background job worker or from the main app.
This header is used later to know in a quick way how much the node is far from full sync and as a result whether to show a blocking sync ui on start.
=> Cache last synced header timestamp

app.go, app_init.go, backup/crypto.go, backup/drive.go, backup/init.go, backup/interface.go, backup/manager.go, backup/manager_test.go, bindings/api.go
This PR adds the ability to set an encryption key to the `backup.Manager` to be used when encrypting the files before uploading them using the chosen provider.
The encryption key is optional and if not set the files won't be encrypted.
When the encryption key is used in a specific backup, the "Snapshot" is marked as encrypted (using custom property in Gdrive provider for example). This is so we know in the restore flow for each snapshot if it requires a key to decrypt the files.
We can also use this mark to differentiate encrypted snapshots from non-encrypted ones in the UI (show lock icon or similar...).
The PR is backward compatible and also add some tests for this new flow.
=> Allow use security key to encrypt backup files.

bindings/api.go, swapfunds/addfunds.go
This PR fixes the submarine swap flow where user sends additional money to a sub swap address after the swap was completed.
Currently such kind of addresses are ignored, leaving the user with uncertainty.
The code change is to identify such cases and mark those addresses for a refund.
The fix includes:
1. Remove the filter of addresses we already paid and instead fetch all addresses.
2. Consider all utxos when calculating the LockHeight and not only the first one.
3. In addition the `GetRefundableAddresses` function that is not in use anymore was removed.
=> Subswap multi utxo fix

account/account.go
This PR adds a safety mechanism for https://github.com/lightningnetwork/lnd/issues/3429 until we understand how/if this should be solved in LND.
We take into consideration additional threshold of half of commit fee to cover cases where the commit fee changes and not allowing spend/receive using the channel.
Whether to use this threshold when calculating maxReceive or maxPay per channel is determined by who is the initiator which currently is the commit fee payer.
=> Considering the commit fee possible change

commands.go, lnnode/client.go, lnnode/daemon.go, lnnode/init.go, lnnode/notifier.go
This PR adds two commands that accessible for the user from the dev interface:
querymc - which shows the mission control snapshot.
resetmc - which reset the historical mission control data.
=> Add mission control commands to RPC interface.

bindings/api.go, chainservice/bootstrap.go
This PR adds API in breez library to reset the chain service information.
More specifically delete neutrino headers, filters and db files.
The effect of this is that on next restart they will be rebuilt again allowing recovery in case of corruption.
=> implement api to reset chain service information.

db/funds.go, swapfunds/removefunds.go
This PR ensures we don't try to redeem funds from the swapper unless we know we paid the invoice.
This ensures we won't retry redeem funds that we don't deserve and risk in falling into rate limit error.
=> Optimize remove funds

swapfunds/addfunds.go
This PR fix an issue where the clients tries to create invoice for the swapper fails and no error is shown to the user.
The fix is to associate the error with the swapAddressInfo as we are doing in other error cases.
=> Mark swap error in case of fail to create invoice.

swapfunds/addfunds.go
Before this PR we marked addresses with positive confirmed amount as "confirmed".
The "confirmed" addresses should be such that we need to redeem payments for them.
This created a bug where when we got the lightning payment as part of the swap the address stayed as "confirmed" since its confirmed amount hasn't change (it will only change after the server has redeemed and confirmed).
The client mistakenly tried to redeem repetitively, showing UI for "transferring funds..."
This PR ensures that addresses that we already paid are not candidate for a swap and won't marked as confirmed.
If use has sent funds to this address after we paid it will be shown as refundable.
=> addfunds: don't mark paid address as confirmed.

app.go, backup/crypto.go, backup/drive.go, backup/init.go, backup/interface.go, backup/manager.go, backup/manager_test.go, bindings/api.go
This PR is a preparation of the code to be able to get more than one key type for the encryption key.
In general it simplify the API by only require that the key will be 256 bit length and removes the hashing that was done previously.
This enables the upper layer (UI) to send raw keys generated from different sources (like mnemonics) and keep the key type as metadata for the backup snapshot.
The key type is then used in restore by the upper layer to choose the interface for the user.
in drive the key type metadata is saved under a new metadata key: "`backupEncryptionTypeProperty`" and maintains backward compatibility with the old deprecated key: "`backupEncryptedProperty`"
=> Prepare mnemonics backup

bindings/native_backup_provider.go
This PR adds the ability to inject a backup provider from upper layers.
For some backup providers implementation, like iCloud, it is more natural to use the native API rather than be implemented in go.
The PR does the following:
1. Define a "`NativeBackupProvider`" interface to be implemented by the native layer.
2. Implement a "`NativeBackupProviderBridge`" that bridges the above interface with the real backup provider interface exists in the `backup` package.
3. Add endpoint to register a native backup provider.
=> Native backup provider

backup/drive.go, backup/interface.go, backup/manager.go, backup/manager_test.go, bindings/native_backup_provider.go
This PR changes the interface of the "UploadBackupFiles" of the backup provider to return also the account name on behalf of which the backup was executed.
This is to enable the higher level layer to present this account as part of the last successful backup.
=> Add accountName to the return value of UploadBackupFiles.

db/db.go
If the path is needed, it can be retrieved using db.Path(), like in the
DeleteDB() method.
=> Remove unused dbPath member variable

app_init.go, bindings/api.go, lnnode/daemon.go, lnnode/init.go
This PR makes sure the syncBeforeStart is false in case we recover the chain information by deleting neutrino files.
At this case we prefer the app will make sure it is synced to chain before LND starts its all sub systems.
=> Sync on reset chain

account/payments.go
This PR adds the network info into payment failure reports.
This will help detect those failures that are caused by in-complete graph.
=> add network info in payment failure.

account/chain.go, bindings/api.go, lnnode/client.go, lnnode/daemon.go, lnnode/init.go, lnnode/notifier.go
In this PR we use the walletKit rpc to query the fee instead using the  static fee estimator.
This with the addition of configuring lnd with "neutrino.feeurl"  we are able to know the fee rate in realtime.
=> Dynamic fee estimate

chainservice/init.go, drophintcache/drophintcache.go, go.mod, go.sum
This PR update the dependencies to support utxo scanner progress and by that allows us not to persist the filters to disk.
In addition it also fixes a bug when dropping the hint cache.
=> Incremental channels rescan

chainservice/bootstrap.go, chainservice/compact.go, chainservice/init.go
This PR changes the usage of creating neutrino db from both bootstrap and creating chain service to one function `getNeutrinoDb`.
Also we now reset the chain service data in case we failed to purge. It will result in retrieving the headers again from the network.
=> chainservice: reset chain service in case of error in purging.

account/account.go, app_init.go, swapfunds/addfunds.go, swapfunds/init.go
In this PR we use the "FUND_EXCEEDED_LIMIT" error in the following two cases:
1. When invoice value is above max limit of a lightning payment.
2. When invoice value is above node ability to receive (capacity wise).
=> Better expose over the limit swap error.

account/chain.go
This kind of address is not used anymore and we need to consider them as
invalid in order to differentiate Bitcoin addresses from Lightning Network
node ids.
=> Consider pay-to-pubkey addresses as not valid.

account/connect.go, account/init.go, account/payments.go, account/service.go, lnnode/daemon.go, lnnode/init.go
This PR adds a more robust way to know when the client is ready for payment.
In multi channel environment, where some are active and some not, we need also a way to customize the timeout and add a grace period to allow all channel to become active.
I removed the connectNotifier that used a custom channel and now based totally on the daemon state and channel events.
=> More robust way to wait for payment readiness

bindings/api.go, bootstrap/bootstrap.go
This PR adds an endpoint for breez to allow synchronize the network graph from a file.
The file is expected to be bolt db with the same format as the current node channel db.
The sync process is as follows:
1. Delete the zombies bucket from the destination database.
2. Copy the following buckets content from source db to destination db: "graph-edge", "graph-meta", "graph-node" excluding the path: "graph-node.source" which is private to the current node.
The sync process is fast since is done in one transaction. It takes 2.5 seconds on a high end device and ~12 seconds on old devices (iPhone 6).
=> Graph bootstrap

account/payments.go, bindings/api.go, swapfunds/boltzreverseswap.go, swapfunds/init.go, swapfunds/removefunds.go
This PR simplifies the send payment API for both spontaneous and with payment request.
Instead of getting the result asynchronously the result is returned synchronously and includes the trace report.
Only for those pending payments that are found after restart an event is sent with their result in order for the UI to be able to respond.
=> Refactor sendPayment to run synchronously.

account/lnurl.go
I think this does it, still puzzled by the Flutter side though.
But if the Flutter side is sending anything it gets from the QR code scan directly through the Go backend then this should do it.
=> support lnurl fallback scheme.

account/payments.go
This change is to return error when invoice is about to be created with no routing hints since it won't be usable anyway.
=> Return error when no routing hints.

README.md
Fixed #132
I try to build the project and I found this information missing inside the readme.
Without this, an env configured with the modern go lang project format is unable to build the target.
=> Adding build info to the docs.

README.md, build-ios.sh
This PR addresses Issue #137 
GoMobile updated to 100% of the time build xcframeworks instead of fat frameworks.
GoMobile will no longer pay attention to architectures that are passed in.
In addition, it is enforcing that the framework extension be .xcframework.
Added an extra note to the README warning about installing Go from Homebrew.
=> GoMobile broke framework creation

app.go
Ref https://github.com/breez/breezmobile/pull/1043 where is iOS tor implementation is not ready. 
Add check to only allow for activation of tor the OS is android.
This should solve the issue when tor is enabled (android) and restored on iOS ref(https://github.com/breez/breezmobile/pull/1043#issuecomment-1385155711)
=> allow tor iff android

app.go, backup/init.go, backup/manager.go, bindings/api.go
Fixes bug that causes iOS and Android to crash on fresh install. 
The issue where caused by trying to set backupmanagen on an empty provider.
Removed _SetBackupTorConfig_ from the bridge
=> Tor hotfix

README.md, docker/alice/Dockerfile, docker/breez_server/Dockerfile, docker/lspd/Dockerfile
As recorded in the docs, go get -d does not install the binary which is
required in the next step. From `go help get`:
> The -d flag instructs get not to build or install packages. get will only
update go.mod and download source code needed to build packages.
> Building and installing packages with get is deprecated. In a future release,
the -d flag will be enabled by default, and 'go get' will be only be used to
adjust dependencies of the current module. To install a package using
dependencies from the current module, use 'go install'. To install a package
ignoring the current module, use 'go install' with an @Version suffix like
"@latest" after each argument.
[Note](https://github.com/breez/breez/pull/179#issuecomment-1430835571): running `go install golang.org/x/mobile/cmd/gomobile` …
=> doc: Recommend go install rather than go get -d, and bump to go 1.17

account/payments.go, channeldbservice/init.go, lnnode/daemon.go
This PR in the current form makes sure the INVOICE_PAID event is not fired until the underlying htlcs are settled (the commitments containing the htlcs are revoked). The hope is that users would wait with closing the app until they see a checkmark. So delaying the checkmark until the htlcs are finally settled could avoid some force closes.
In order to do that we need to use the new `LookupHtlc` api, which will be added in LND 0.16. So this PR will be dependent on LND releasing the 0.16 version. For this draft PR I've rebased breez/lnd on top of lightningnetwork/lnd@master temporarily. It can be found as this temporary branch: https://github.com/breez/lnd/tree/temp-lnd-merge-0.16 . Upgrading that depends on a later version of btcwallet. So also breez/btcd is updated in a temporary branch: …
=> Await htlc resolution

backup/manager.go
This PR adds some safty mechanism to always backup the node data even if only app data backup is requested.
This is to make sure the snapshot in the cloud always contains some state of the node data and remove the risk of users 
ignoring the warning icon and forgetting to backup at some point in the future.
=> Backup node data even if only app data is requested.

bindings/api.go, services/client.go, services/init.go
Removed the caching of lsp list.
Added caching on one function that relied on the old caching behavior. It only uses the lsp ids and my concern of removing the caching here will cause some performance regressions on breez mobile.
We might decide on higher level to call it less frequently and then we may remove the caching here as well.
=> refresh lsp list on every call

README.md
LND now seems to require Go 1.19, 1.17 and 1.18 no longer work
=> Update the required Go version

docker/dev-simnet.yml, docker/lspd/start.sh, docker/simnet.yml, docker/start-dev-env.sh, docker/start-network.sh
Hey again, the simnet broke again due to recent changes as detailed here: https://github.com/breez/breez/issues/184#issuecomment-1566170899
These are my fixes for the LSPD migrations not being applied and the MEMPOOL_API_BASE_URL not being set. Let me know if any changes are required, I figured the normal mempool API is probably fine however it should be possible to include a local mempool instance in the future: https://github.com/mempool/mempool/tree/master/docker
=> Fix broken simnet

build.sh
Fixes this error:
`gomobile: ANDROID_NDK_HOME specifies /path/to/ndk/25.2.9519653, which is unusable: unsupported API version 16 (not in 19..33)`
=> set minimum android api for gomobile

account/lnurl.go
This fixes issue with lighting addresses where we used https for onion addresses instead of http.
=> use http if onion address

docker/alice/Dockerfile, docker/breez/Dockerfile, docker/breez_server/Dockerfile, docker/lnd/Dockerfile, docker/lspd/Dockerfile, go.mod, go.sum, itest/generate_lspd_config.go, itest/tests/open_channel_compat_test.go, itest/tests/subswap_test.go
All dockerfiles for the simnet environment now point to the right repository and to a specific version of that repository. That means if a version is updated, we should update the versions in the dockerfiles here as well.
Small extras:
- Fixed a bug with the lspd .env file
- Use opening_fee_params in the subswap test
Should fix https://github.com/breez/breez/issues/214
=> fix simnet env by pointing to specific versions

go.mod, go.sum
This version of LND contains a potential fix for clients where the channel graph is corrupted due to an invalid channel key.
=> bump lnd version to v0.16.4-breez-2

bindings/api.go
The current logging did not reflect the correct readable value.
Tested with breezmobile.
=> fix logging

go.mod, go.sum
Ensure chain sync always falls back to the p2p peer if the rest peer is (temporarily) unavailable
See https://github.com/breez/neutrino/pull/4
New neutrino branch is https://github.com/breez/neutrino/tree/neutrino-v0.15.0-breez-1
=> neutrino: fallback to p2p peer

sync/channelswatcher.go, sync/job.go
The channels watcher uses the blockheight of channels to determine where to start the rescan. For zero conf channels, however, the short channel id contains the scid alias, so the blockheight is bogus. If the channel is zeroconf, the real blockheight sohuld be taken using `ZeroConfRealScid`.
This caused the chainsync job to fail, because the call to `startHash, err := b.chainService.GetBlockHash(int64(startHeight))` would fail if the blockheight didn't exist.
=> Use the real channel blockheight for rescans

go.mod, go.sum
This neutrino bump changes the 'minimum'/'initial' query timeout from 4 to 10 seconds. The maximum timeout is bumped from 32 to 40 seconds.
=> bump neutrino

closedchannels/job.go, sync/job.go
Sometimes multiple sync jobs and/or multiple closedchannels jobs are run at the same time. This PR ensures the job is cancelled if another job is already running.
=> ensure a single job is run at once

account/lnurl.go
Same as https://github.com/breez/breez-sdk-greenlight/pull/1097
=> strip ₿ prefix from lightning addresses

app.go, db/syncstatus.go, lsp_chan_state.go
The recordChannelsStatus function would insert all zero conf channels into the channelOpeningState bucket. This causes the funding workflow for these channels to restart. When the funding flow restarts, LND will start searching for the funding transaction by scanning the chain backwards. This means as you have channels for a longer time, Breez would consume more and more bandwidth to sync the chain from tip to channel open height. By deleting this function, once the funding workflow is complete once, it won't be entered again.
Upon cleaning up it seems that SetMismatchedChannels was never used. So FetchMismatchedChannels and RemoveChannelMismatch could be removed as well.
=> remove record channels status
