breez/breez

- account.go
- init.go
This PR ensures the channel between the breez node and the mobile node keep retry until success.
> Retry channel in case fail.

- account.go
- bindings/api.go
- connect.go
- init.go
This PR handles two things:
1. Move all the connection logic to its own file separated from the account logic
2. Add ConnectAccount API to breez library.
> Connect api

- bindings/api.go
- init.go
This PR ensures:
1. Breez can not be started twice without stop int between.
2. Breez uses signal to stop rather then RPC which might not be available.
> Reliable stop

- init.go
This PR optimize startup time by not trying to connect manually when we already having a channel or pending channel.
In this case lightningLib will attempt to connect automatically on startup and we can save a cancelled connection.
> fast startup, ignore manual connection when has channel.

- backup/drive.go
This PR makes sure that the uploaded backup files are exactly
the files we requested to upload by validating the checksum returned
from google drive to our own calculated checksum.
> backup: add MD5 checksum validation on uploaded files.

- backup_listener.go
- go.mod
- go.sum
- init.go
This PR connects the backup events triggered from lightningLib to a real backup request to the BackupManager.
It adds a watcher that registers a listener via RPC and for each event it requests a backup.
> Listen backup events

- bindings/api.go
- config/init.go
- payments.go
In this PR we add an API endpoint in breez to send bug reports.
The PR includes:
1. Change configuration to add "bugreporturl"
2. Extract relevant information (payment request, amount, query routes, etc...) and send it to bug report service.
3. Add binding for mobile.
> Payment failures bug report

- backup/init.go
- backup/manager.go
- bindings/api.go
- bindings/native_backup_provider.go
This PR add endpoint in breez to set backup provider. This endpoint can be called any time after the BackupManager has been created and the new provider will take effect immediately.
> Allow switch of backup provider

- app.go
- chainservice/compact.go
- chainservice/init.go
- go.mod
- go.sum
This PR imlements purging the filters from the neutrino db and run compact if the db grows over 150m.
This makes sure the db file will stay in a reasonable size and we won't crash on memory consumption.
> chainservice: purge filters on synced to chain and compact over 150m.

- account/sweep.go
When calculating 3 different transactions with different fees for sweeping all coins, we need to ignore those invalid transactions that yields negative outputs.
> Skip transactions with negative outputs.

- app.go
- bindings/api.go
- go.mod
- go.sum
After restarting the app, the updated channel policy will be downloaded
again.
> Add a function to delete the channels of a specific node form the graph.

- sync/channelswatcher.go
This PR addresses an issue where the channels watcher background job always started from the funding transaction block when it was interrupted and didn't finish its scan.
Now we both update the progress every 100 blocks and use the hint cache to better get the starting point for the scan.
> Incremental channel watcher.

- account/payments.go
Small PR that fix the user error when no route is found.
> Return no route in case max payment is zero

- account/lnurl.go
- data/messages.proto
This depends on https://github.com/breez/breezmobile/pull/560.
> Lightning-Address (sending)

- account/connect.go
To replicate the test:
cd account
go test -run ".*"
> Fix payment tests

- .gitignore
- go.mod
- go.sum
One step more for https://github.com/breez/breezmobile/issues/977
> Update go lnurl lib

- go.mod
- go.sum
Added better logging to neutrino branch.
> bump neutrino version

- build-ios.sh
Updated the build script for ios in order to match the build script with the github workflow which builds for simulator and device.
> match build script with workflow

- docker/breez_server/Dockerfile
- docker/lspd/Dockerfile
- docker/lspd/start.sh
- docker/simnet.yml
- docker/start-dev-env.sh
- itest/generate_lspd_config.go
Ensures that Breezmobile can connect to and benefit from the functionality of LSPD. Before these fixes the mobile application tries to connect to the wrong IP address so they can't receive incoming payments.
Thanks a lot to @roeierez for helping me out and fixing a lot of the issues I encountered
> Fix the broken simnet configuration

- sync/channelswatcher.go
In addtion wait at least 144 blocks before notifying.
> Only notify closed channels over 1000 sats.

- account/lnurl.go
- app.go
- go.mod
- go.sum
This pr references the issue brought up in this discussion https://twitter.com/openoms/status/1632033974351478785 where onion lnurls where not properly handled. 
https://twitter.com/ubbabeck/status/1634571666628943873
Tested with the static lnurl given in the discussion mentioned above. 
Will need to conduct some more tests, any ideas on what this change might break ?
> add torclient to handling onion lurls

- account/lnurl.go
Related to https://github.com/lnurl/luds/pull/234 
Tested with breezmobile and calle@legend.8333.space
> Drop metadata description hash validation

- closedchannels/job.go
Add a one-time patch for re-initiating closed channel downloads.
It depends on a file specific to this patch existing in the 'pruned' folder.
If the file is there, that means the patch has been applied.
If the file is not there, that means we have to re-initiate the closed channel downloads, but only if the directory already existed.
> one-time patch to re-initiate closed channel downloads

- closedchannels/job.go
Some lines were using the wrong logger
> fix lines using wrong logger

- account/payments.go
closes 
- https://github.com/breez/breezmobile/issues/1266
> Convert amounts in `addInvoice` errors & logs to use Sats

- account/payments.go
- go.mod
- go.sum
Improve payment logging in LND.
Also fix the XImportMissionControl call, which failed with error: `[ERR] RPCS: [/routerrpc.Router/XImportMissionControl]: invalid vertex length of 66, want 33`
> improve payment logging

- account/payments.go
Log the routes used for payments so we can debug failing payments better.
> pay: log routes used

- account/payments.go
This change fixes the fee limit logging for this line https://github.com/breez/breez/blob/de52012318c8966eda4f6cab851997f0afb20255/account/payments.go#L424
> set fee limit msat instead of fee limit sat

- account/account.go
Should fix https://github.com/breez/breez/issues/255
Source: https://github.com/breez/lnd/blob/8da68bb7dbf0423bb8c9e13dcfa982f80a9aabe3/lnwallet/channel.go#L8269-L8395
The main thing that changed in LND is `applyCommitFee` now includes a buffer amount of 2x the current chain fees + 1 additional htlc.
> compute correct max receivable
